language: java

os:
- linux
- osx

dist: trusty
osx_image: xcode9.2

sudo: true

env:
  global:
  - LD_LIBRARY_PATH=/usr/local/lib
#  - JAVA_HOME=$(/usr/libexec/java_home)
  - LIBSTORJ_VERSION=2.0.0-beta2

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    apt-get install build-essential libtool autotools-dev automake libmicrohttpd-dev bsdmainutils
    apt-get install libcurl4-gnutls-dev nettle-dev libjson-c-dev libuv1-dev
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install -v libtool automake libmicrohttpd pkgconfig
    brew install -v curl nettle json-c libuv
  fi

install:
- curl -sSL https://github.com/Storj/libstorj/archive/v$LIBSTORJ_VERSION.tar.gz | tar -zxv
- (cd libstorj-$LIBSTORJ_VERSION && ./autogen.sh && CC=clang CFLAGS="-g -O2 -O3 -std=gnu99" ./configure && make && sudo make install)

script:
- LD_LIBRARY_PATH=$(pwd)/libstorj-$LIBSTORJ_VERSION/lib:/usr/local/lib:/usr/local/opt/curl/lib INCLIDE=$(pwd)/libstorj-$LIBSTORJ_VERSION/include ./gradlew jniSharedLibrary --info
- ./gradlew build

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/Library/Caches/Homebrew"

before_deploy:
- cd build/libs/jni/shared/
- cp /usr/local/lib/libstorj.2.dylib .
- cp /usr/lib/libcurl.4.dylib .
- cp /usr/local/opt/nettle/lib/libnettle.6.dylib .
- cp /usr/local/opt/json-c/lib/libjson-c.2.dylib .
- cp /usr/local/opt/libuv/lib/libuv.1.dylib .
- chmod 666 *.dylib
- install_name_tool -id libstorj.2.dylib libstorj.2.dylib
- install_name_tool -id libcurl.4.dylib libcurl.4.dylib
- install_name_tool -id libnettle.6.dylib libnettle.6.dylib
- install_name_tool -id libjson-c.2.dylib libjson-c.2.dylib
- install_name_tool -id libuv.1.dylib libuv.1.dylib
- install_name_tool -change /usr/local/lib/libstorj.2.dylib libstorj.2.dylib libstorj-java.dylib
- install_name_tool -change /usr/lib/libcurl.4.dylib libcurl.4.dylib libstorj-java.dylib
- install_name_tool -change /usr/local/opt/json-c/lib/libjson-c.2.dylib libjson-c.2.dylib libstorj-java.dylib
- install_name_tool -change /usr/local/opt/nettle/lib/libnettle.6.dylib libnettle.6.dylib libstorj-java.dylib
- install_name_tool -change /usr/local/opt/libuv/lib/libuv.1.dylib libuv.1.dylib libstorj-java.dylib
- install_name_tool -change /usr/lib/libcurl.4.dylib libcurl.4.dylib libstorj.2.dylib
- install_name_tool -change /usr/local/opt/json-c/lib/libjson-c.2.dylib libjson-c.2.dylib libstorj.2.dylib
- install_name_tool -change /usr/local/opt/nettle/lib/libnettle.6.dylib libnettle.6.dylib libstorj.2.dylib
- install_name_tool -change /usr/local/opt/libuv/lib/libuv.1.dylib libuv.1.dylib libstorj.2.dylib
- tar -zcf java-libstorj-$TRAVIS_TAG-macos-dylibs.tar.gz *.dylib
- cd ../../../../

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: BFNGvCiVL/G9yAM5b7rqlicCttonF2E84jNVG4SIfNj08DgeIP0w/v8XTwHvCP9/Frt0+1X9GM3BY1VmBLxe7I5lLOd2E7fz28p+DAZL35yLqrEYTbzwb6/mFxVyOnUM3vjIbH0/Jnf5uCXwzG8gYvhZQBDG2GMmx6C/BqDfEB3yFCG3GKwVi9BhzR7kL123pfa+ZwC2n0zh7Rmslu2uwhxJ+jxSAUofO9VWyBhSmxIc6JxJV1hxQPnwzZh4zTh5kmzVhjh8YCPABeNueL1Kzo6G+4Yp8K6FnxltsbzBruqk9kFxKes/9xwDT6Ym6HNRf+Zy0fE/s1mKiJ1N8+HamvFE8v7mUCuIn3wPNcpP2ytg0kB0auPRHcxaQwth3So9ys+yKv4P1Mg/DeyxkIiS2M02wj4lQqENsIOfNchDP/qMMQ06ePjBh5bLqy91Rcu7SQAx/uMxVMdTyv5cJAAueV0fMyrjt+feCnZvwK9/jA2xktFcyKeBLYaeaS5sX8kZjK2i1KBsDLTPlPd+R5B+xyja/FKJy8OkEGhSYWPhB6vgRRmoyvy+qTwqnegvwp8xc86dHKAZmzofE5u4Eq+suklOi0F3ejCUT/a7rzlgNVxg4+GcWeSYtDjLnp8ITo3QsACTW7SzbvZ5yIealdJMro+LWCYb7HLhkOBjYy1Gymo=
  file:
  - build/libs/jni/shared/java-libstorj-$TRAVIS_TAG-macos-dylibs.tar.gz
  on:
    repo: Storj/java-libstorj
    tags: true
